name: dart_counter
description: A base to build a flutter app up on following the domain driven
  development style

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_game:
    path: packages/dart_game
  dart_client:
    path: packages/dart_client
  social_client:
    path: packages/social_client

  async: ^2.8.1
  auto_route: ^2.4.1
  auto_size_text:  3.0.0-nullsafety.0
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.3
  connectivity_plus: ^1.1.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.1
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  faker: ^2.0.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter_bloc: ^7.3.0
  flutter_facebook_auth: ^3.5.2
  flutter_hooks: ^0.18.0
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.8
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_sign_in: ^5.1.1
  image_picker: ^0.8.4+2
  injectable: ^1.5.0
  kt_dart: ^0.9.1
  lottie: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.1
  responsive_builder: ^0.4.0-nullsafety.1
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  sign_in_with_apple: ^3.2.0
  timeago: ^3.1.0
  touchable: ^1.0.0
  url_launcher: ^6.0.12
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.4.1
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  freezed: ^0.14.5
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.2
  lint: ^1.7.2
  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/animations/
    - assets/images/png/
    - assets/images/png/2.0x/
    - assets/images/png/3.0x/
