name: dart_counter
description: A base to build a flutter app up on following the domain driven
  development style

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  dart_game:
    path: packages/dart_game
  dart_client:
    path: packages/dart_client
  social_client:
    path: packages/social_client

  async: ^2.8.1
  auto_route: ^3.1.3
  auto_size_text:  ^3.0.0
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.5
  cloud_functions: ^3.2.4
  connectivity_plus: ^2.1.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.4
  dartz: ^0.10.0-nullsafety.1
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  faker: ^2.0.0
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  flutter_bloc: ^8.0.0
  flutter_facebook_auth: ^3.5.7
  flutter_hooks: ^0.18.1
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.8
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  injectable: ^1.5.0
  kt_dart: ^0.10.0
  lottie: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.1
  responsive_builder: ^0.4.0-nullsafety.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11
  sign_in_with_apple: ^3.3.0
  timeago: ^3.1.0
  touchable: ^1.0.0
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  json_annotation: ^4.4.0
  bloc_concurrency: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3
  lint: ^1.8.1
  flutter_lints: ^1.0.4
  fake_cloud_firestore: ^1.2.0
  firebase_storage_mocks: ^0.5.0
  firebase_auth_mocks: ^0.8.1
  google_sign_in_mocks: ^0.2.1
  bloc_test: ^9.0.1
  mocktail: ^0.2.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/animations/
    - assets/images/png/
    - assets/images/png/2.0x/
    - assets/images/png/3.0x/
