name: dart_counter
description: A base to build a flutter app up on following the domain driven
  development style

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.2"

dependencies:
  flutter:
    sdk: flutter
  dart_game:
    path: packages/dart_game
  dart_client:
    path: packages/dart_client
  social_client:
    path: packages/social_client

  async: ^2.8.2
  auto_route: ^3.2.4
  auto_size_text:  ^3.0.0
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.8
  cloud_functions: ^3.2.7
  connectivity_plus: ^2.2.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  faker: ^2.0.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^4.0.1
  flutter_hooks: ^0.18.2+1
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.8
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+9
  injectable: ^1.5.3
  kt_dart: ^0.10.0
  lottie: ^1.2.2
  modal_bottom_sheet: ^2.0.0
  provider: ^6.0.2
  responsive_builder: ^0.4.0-nullsafety.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^3.3.0
  timeago: ^3.2.2
  touchable: ^1.0.0
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  json_annotation: ^4.4.0
  bloc_concurrency: ^0.2.0
  logger: ^1.1.0
  quiver: ^3.0.1+1
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  lint: ^1.8.2
  flutter_lints: ^1.0.4
  fake_cloud_firestore: ^1.2.1
  firebase_storage_mocks: ^0.5.0
  firebase_auth_mocks: ^0.8.2
  google_sign_in_mocks: ^0.2.1
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  mockingjay: ^0.2.0
  source_gen: ^1.2.1

dependency_overrides:
  test_api: 0.4.9

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/animations/
    - assets/images/png/
    - assets/images/png/2.0x/
    - assets/images/png/3.0x/
